Feature/#10 filter samples
NIVANorge/odm2-postgres-api pull request #103
Opened 2021-01-18 20:27 UTC by jemmima

Add an annotation for mass spec samples to annotations table and create samplingfeatureannotations for each new sample registered by mass-spec-api. To follow I will modify the api query from mass-spec-ui to fetch only the mass spec samples. This pr is independent so can be merged before that is done.

2021-01-18 20:30 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
This is the main part I am unsure of - I tested it and it works, but I'm not sure if this is good practice or the right place for it. Should it be in register_sample or somewhere else? 🤔

2021-01-19 11:48 UTC, ZofiaRudjord requested changes

2021-01-19 11:48 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
You already created annotation in mass_spec_metadata and now you want to link it to the samplingfeature you create. I think you can re-use the annotation field in SamplingFeaturesCreate. You can get the annotation id via fetch_row.

2021-01-19 12:18 UTC, RmStorm requested changes
I agree with @ZofiaRudjord that the annotationid should be fetched instead of hardcoded. It can also be added directly to the samplingfeaturecreate query instead of being it's own query.

Also, in the save_annotations function it's better to use find_row on the annotationtext instead of the annotationtypecv.

2021-01-19 12:18 UTC, RmStorm commented on src/odm2_postgres_api/queries/storage.py
> +    existing = await find_row(connection, "annotations", "annotationtypecv", annotation.annotationtypecv, Annotations)
I don't think this should try to find a row based on `annotationtypecv` it should look at the `annotationtext` instead. That is still not 100% solid since annotationtext doesn't have a unique constraint. It should however be solid enough to find the annotation with text: "Mass spectrometry sample".

2021-01-19 12:18 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
yeah I agree, the `annotationid` can be added directly to the `SamplingFeaturesCreate` on line 226 like so:
```python
            mass_spec_annotation = await find_row(conn, "annotations", "annotationtext",
                                                  "Mass spectrometry sample", schemas.Annotations)
            sampling_feature = schemas.SamplingFeaturesCreate(
                samplingfeatureuuid=uuid.uuid4(),
                samplingfeaturecode=data.samplingfeaturecode,
                samplingfeaturetypecv="Specimen",
                relatedsamplingfeatures=[(data.parent_samplingfeatureid, "Was collected at")],
                annotations=[mass_spec_annotation.annotationid]
            )
```

2021-01-19 12:18 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
Fetching the `annotationid` like that instead of hardcoding `15` is more solid I think!

2021-01-19 12:24 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
🤦‍♀️  of course!! How's this @ZofiaRudjord ?

```
async def register_sample(conn: asyncpg.connection, data: schemas.MsCreateSample) -> int:
    """
    This function registers the main sample collected in samplingfeature table.
    """
    async with conn.transaction():
        samplingfeatureid = await get_samplingfeatureid_from_samplingfeaturecode(conn, data.samplingfeaturecode)
        if samplingfeatureid is None:

            annotationid = await conn.fetch(
                "select annotationid from annotations a "
                "where annotationtext = 'Mass spectrometry sample'"
            )

            sampling_feature = schemas.SamplingFeaturesCreate(
                samplingfeatureuuid=uuid.uuid4(),
                samplingfeaturecode=data.samplingfeaturecode,
                samplingfeaturetypecv="Specimen",
                annotations=[annotationid],
            )

            ms_sample_data = schemas.ActionsCreate(
                actiondescription="Registered water sample",
                begindatetime=datetime.utcnow(),
                actiontypecv="Specimen collection",
                methodcode="mass_spec:collect_sample",
                isactionlead=True,
                sampling_features=[sampling_feature],
                affiliationid=1,
                begindatetimeutcoffset=0,
            )

            completed_sample = await core_queries.do_action(conn, ms_sample_data)
            samplingfeatureid = completed_sample.sampling_features[0].samplingfeatureid

    return samplingfeatureid
```

2021-01-19 12:40 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
Doing it this way will also create the bridge between annotation_id created during metadata startup and 
sampling_feature_id

2021-01-19 12:41 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
Ah you beat me to it! I just pushed this but my find_row is different 🤔. Should I change to what you have here @RmStorm ?

2021-01-19 12:42 UTC, jemmima commented on src/odm2_postgres_api/queries/storage.py
> +    existing = await find_row(connection, "annotations", "annotationtypecv", annotation.annotationtypecv, Annotations)
Yes I totally agree!!

2021-01-19 13:05 UTC, jemmima commented on src/odm2_postgres_api/queries/storage.py
> +    existing = await find_row(connection, "annotations", "annotationtypecv", annotation.annotationtypecv, Annotations)
Changed in ef2f5ff. Is this ok now?

2021-01-19 13:07 UTC, jemmima commented on src/odm2_postgres_api/queries/storage.py
> +    existing = await find_row(connection, "annotations", "annotationtypecv", annotation.annotationtypecv, Annotations)
Changed in ef2f5ff, is this ok now?

2021-01-19 13:10 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            await core_queries.create_sampling_feature_annotation(conn, sampling_feature_annotation_create)
> Doing it this way will also create the bridge between annotation_id created during metadata startup and
> sampling_feature_id

The way I had it did create the bridge because create_sampling_feature_annotation does this and checks if the annotation exists already, but it was hardcoding the annotation_id, which I suppose could be different for every metadata startup? Either way I totally agree that the find_row is better for several reasons!

2021-01-19 13:14 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/storage.py
> +    existing = await find_row(connection, "annotations", "annotationtypecv", annotation.annotationtypecv, Annotations)
Looks good!

2021-01-19 14:11 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotationid = await find_row(conn, "annotations", "annotationtext", "Mass spectrometry sample", schemas.Annotations)
I think find_row returns the entire annotation, not just the annotationid..

2021-01-19 14:17 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotationid = await find_row(conn, "annotations", "annotationtext", "Mass spectrometry sample", schemas.Annotations)
hmm 🤔  that makes sense but why does this work? 😅

2021-01-19 14:24 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotationid = await find_row(conn, "annotations", "annotationtext", "Mass spectrometry sample", schemas.Annotations)
Changed in 73816a5!

2021-01-19 14:41 UTC, RmStorm approved these changes
LGTM! Maybe there should be a note on the `annotation_text` `find_row` bit that there is a potential bug hiding there due to lack of a unique constraint.

Should we add a joint unique constraint on the `annotationtype` and the `annotationtext`? These are the only two columns that are obligatory in the annotations table. A joint unique constraint would allow us to query for that without ever hitting a duplicate and I think it might make sense anyways :thinking: @ZofiaRudjord @jemmima what do you think?

2021-01-19 14:43 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotationid = await find_row(conn, "annotations", "annotationtext", "Mass spectrometry sample", schemas.Annotations)
I think it worked because the Annotation type is derived from the AnnotationCreate type which was also valid instead of an id for identifying the annotation...

2021-01-19 14:43 UTC, jemmima commented
> LGTM! Maybe there should be a note on the `annotation_text` `find_row` bit that there is a potential bug hiding there due to lack of a unique constraint.
> 
> Should we add a joint unique constraint on the `annotationtype` and the `annotationtext`? These are the only two columns that are obligatory in the annotations table. A joint unique constraint would allow us to query for that without ever hitting a duplicate and I think it might make sense anyways 🤔 @ZofiaRudjord @jemmima what do you think?

We would have to change how the result annotations are working now because they are not unique:
![Uploading Screenshot 2021-01-19 at 15.43.04.png…]()

2021-01-19 16:21 UTC, jemmima commented
I have added annotations for replica registration as well following a conversation on slack with @ZofiaRudjord and @RmStorm be82c37

2021-01-20 07:18 UTC, haakondr approved these changes

2021-01-20 07:54 UTC, RmStorm approved these changes
Looks good to me! I have made a final comment about changing a variable name :grin: It's optional so feel free to ignore it!

2021-01-20 07:54 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +        parameters_annotation_id = schemas.AnnotationsCreate(
Can this variable be renamed to `parameters_annotation` since it's not and id but the entire annotation?

2021-01-20 10:25 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +        parameters_annotation_id = schemas.AnnotationsCreate(
Yes! I didn't actually change this part and I didn't notice it was incorrect.

2021-01-20 12:15 UTC, RmStorm commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotations=[parameters_annotation.annotationid, ms_annotation.annotationid],
This list `annotations` accepts both integers or `AnnotationsCreate` objects. So it should be:
```python
annotations=[parameters_annotation, ms_annotation.annotationid]
```
and that will fix the failing test ^^

2021-01-20 12:17 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotations=[parameters_annotation.annotationid, ms_annotation.annotationid],
we are on it!

2021-01-20 12:27 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +        parameters_annotation_id = schemas.AnnotationsCreate(
It wasn't incorrect! I was confused. Fixed now in

2021-01-20 12:27 UTC, jemmima commented on src/odm2_postgres_api/queries/mass_spec_select_queries.py
> +            annotations=[parameters_annotation.annotationid, ms_annotation.annotationid],
Thanks! Fixed in 30d3361

2021-01-20 12:35 UTC, ZofiaRudjord approved these changes
LGTM

2021-01-20 12:36 UTC, merged