Upserting QC
NIVANorge/odm2-postgres-api pull request #123
Opened 2021-06-02 12:35 UTC by ZofiaRudjord

Adding a new unique constraint on TimeSeriesResultValues which required all column values except qualitycodecv to be unique, updating qc on violation of this constraint. Solves #120

2021-06-03 14:19 UTC, knl88 commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
Don't think all_but_qc_unique follows the naming for used in the schema. Should probably be something like fk_TimeSeriesResultValues_....

2021-06-04 08:50 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
fk_ indicates that it is a foreign key, and in this case it is not, it is a unique constraint.

Quick googling suggests the following naming convention:

UQ_<TableName>_<ColumnName(s)>

I don't have any strong opinions on this, but it is perhaps a good idea to continue on the naming convention used (<type of constraint>_<table>_<columns>

2021-06-04 10:08 UTC, haakondr requested changes

2021-06-04 10:08 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
Kim pointed out that this does not drop the current existing unique constraint, but only creates a new one.

Will need to add a statement which drops timeseriesresultvalues_resultid_datavalue_valuedatetime_val_key here. Since this script runs on each app startup, it would have to also work if it does not exist.

2021-06-04 10:08 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
May want to omit CensorCodeCV from this unique constraint? I am not 100% sure about the usage of censorcode, but to me it seems like we'd only want one value per resultid/time.

2021-06-04 10:08 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +        return await conn.fetchrow(upsert_ts_all_but_qc_unique("timeseriesresultvalues", data), *data.values())
as discussed with kim, would be good to have a unit test on this function. should be fairly straight forward, can copy the setup in test_storage.py or any of the other files. 

Running tests is not really documented, there are some quirks, I went through most of them with Kim. 

- working directory needs to be in the project root (so that integration-test-docker-compose.yml gets properly picked up).
- a new test file needs to import the following for the fixtures to work:

```
from integration_test_fixtures import wait_for_db, db_conn
```

This would be solved by renaming integration_test_fixtures.py -> conftest.py

- pytest need to be executed with  `-m docker` in order to run the tests annotated with @pytest.mark.docker

2021-06-04 13:06 UTC, knl88 commented on src/odm2_postgres_api/queries/core_queries.py
> +        f"qualitycodecv='{data['qualitycodecv']}' returning *"
One option could also be to use excluded.qualitycodecv,  created a branch with it https://github.com/NIVANorge/odm2-postgres-api/blob/7d8660e26a54452935d94dbeb325b77b2d0d2811/src/odm2_postgres_api/queries/core_queries.py#L40

2021-06-07 07:51 UTC, ZofiaRudjord commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
I had a problem to drop the constraint, probably syntax again...
In any case I left the constraint because it is less restrictive than the one I added. So my logic was that the one I added will fire first no matter and I tested the code that I can upsert. 
Do you think it is important to delete the constraint?

2021-06-07 07:55 UTC, ZofiaRudjord commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
Regarding naming, it is a good idea to have a system for that. Prepending with uq_ sounds good to me.
How about uq_all_but_qc ?

2021-06-07 08:09 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
about not dropping constraint: we could probably keep it, don't think it matters much

2021-06-07 08:13 UTC, knl88 commented on src/odm2_postgres_api/queries/core_queries.py
> +        return await conn.fetchrow(upsert_ts_all_but_qc_unique("timeseriesresultvalues", data), *data.values())
@ZofiaRudjord  I Added some tests to https://github.com/NIVANorge/odm2-postgres-api/blob/7d8660e26a54452935d94dbeb325b77b2d0d2811/tests/test_core_queries.py#L234 if you want them:)

2021-06-07 09:12 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +        f"qualitycodecv='{data['qualitycodecv']}' returning *"
hm yes, that approach could probably work. I have not used EXCLUDED before, but seems useful.

2021-06-07 12:31 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/core_queries.py
> +        f"qualitycodecv='{data['qualitycodecv']}' returning *"
I updated the code to use the EXCLUDED alias as suggested by @knl88 . I updated however, his proposed unique constraint to be applied to all columns but the two qc ones:  qualitycodecv and CensorCodeCV and therefore to update only these two values on conflict.

2021-06-07 12:31 UTC, ZofiaRudjord commented on src/odm2_postgres_api/queries/core_queries.py
> +        return await conn.fetchrow(upsert_ts_all_but_qc_unique("timeseriesresultvalues", data), *data.values())
I merged @knl88 tests to this branch.

2021-06-07 12:32 UTC, ZofiaRudjord commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.TimeSeriesResultValues ADD CONSTRAINT all_but_qc_unique UNIQUE(ResultID, DataValue, ValueDateTime, ValueDateTimeUTCOffset, CensorCodeCV, TimeAggregationInterval, TimeAggregationInter
Agree, this code is now updated as well and excluded from unique constraint.

2021-06-07 13:51 UTC, haakondr approved these changes

2021-06-07 13:51 UTC, haakondr commented on tests/test_core_queries.py
> +        if k != new_key:
so, the behaviour is that datavalue is never updated, but silently ignored in case of duplicates (?)

Suggest we look at a way to throw errors if it happens that a) we already have a value  and b) the value differs. But, I don't think this blocks a merge and is only a future improvement.

2021-06-07 13:51 UTC, haakondr commented on tests/test_core_queries.py
> +            assert base_row[k] == actual_row[k]
Looks good. 

Possible future improvements on the tests: Could be good to expand this test to check that the values are actually stored. Here we are only testing the response.

Could the core_queries.find_timeseries function be suitable for this? That would also add test coverage to this function.

2021-06-07 13:55 UTC, ZofiaRudjord commented on tests/test_core_queries.py
> +        if k != new_key:
The idea is that it never happens , but you are right, the code should throw error if/when it happens. :-)

2021-06-07 14:14 UTC, knl88 approved these changes
lgtm, guess I can try to wrap my head around other test cases when needed:)

2021-06-07 14:16 UTC, merged

2021-06-07 14:32 UTC, knl88 commented on tests/test_core_queries.py
> +        if k != new_key:
Yeap, guess this can give various unintended effects that we need to think of in the future.