Allow longer samplingfeaturecode and add combinefeatures method.
NIVANorge/odm2-postgres-api pull request #176
Opened 2021-10-28 14:27 UTC by jemmima

Linked prs:
https://github.com/NIVANorge/nivacloud-mass-spectrometry/pull/40
https://github.com/NIVANorge/mass-spec-ui/pull/80

2021-11-08 12:56 UTC, jemmima commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
this is to allow for some of the longer filenames from mass spec - we should think about changing this later but for now the whole pipeline is set up to have the filename stored as the samplingfeaturecode.

2021-11-09 12:59 UTC, ZofiaRudjord approved these changes
LGTM!

2021-11-16 10:35 UTC, haakondr requested changes
the database change won't be applied, see my other comment

2021-11-16 10:35 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
This won't be applied on an existing database. This script just run plain sql statements and fail (gracefully) if table exist.

In other words, if ODM2.SamplingFeatures table already exists you need to perform a alter table statement, something like:

```
alter table ODM2.SamplingFeatures alter column samplingfeaturecode type varchar (100)
```

I have not tried this. need to ensure that not null constraint is not overwritten by this.

2021-11-16 10:36 UTC, haakondr commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
I think longer codes is ok for now, but should probably aim to keep them below 50 or so, as UI's displaying codes typically don't reserve a lot of space to display codes as they should ideally be quite short.

2021-11-17 09:24 UTC, ZofiaRudjord commented
Thanks for catching this @haakondr !  the reason it works locally is because with doco down we wipe the db.

2021-11-17 12:46 UTC, jemmima commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
@ZofiaRudjord is it better to restrict the length of the filename to 50 chars do you think?

2021-11-17 12:48 UTC, ZofiaRudjord commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
Ideally yes, but you had a reason for needing longer codes, right?

2021-11-17 12:49 UTC, jemmima commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
Yes only that some of the test file names had too long codes, so I anticipated this might happen a lot, but might be better to restrict it?

2021-11-18 12:11 UTC, jemmima commented on src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
>  	samplingfeaturename varchar (255) NULL,
Implemented in 113eabc. I tested this locally on an existing odm2 instance and the column is still UNIQUE after, so I'm going to merge it and test in niva test.

2021-11-18 13:26 UTC, merged