dev -> master
NIVANorge/odm2-postgres-api pull request #206
Opened 2022-02-07 08:18 UTC by haakondr

making PR mainly to highlight the schema changes made

2022-02-07 12:38 UTC, haakondr commented on k8s/deployments/deployment-kafka-sink.tmpl.yaml
> +#          initialDelaySeconds: 0
TODO: setup liveness probe

2022-02-07 12:38 UTC, haakondr commented on api/src/odm2_postgres_api/queries/core_queries.py
> -async def find_spectra(conn: asyncpg.connection, samplingfeaturecode: str, raise_if_none=False):
This got moved a bit below in the file causing a bit weird diff here. It seems like they are identical from what I can tell

2022-02-07 12:38 UTC, haakondr commented on api/src/odm2_postgres_api/metadata_init/populate_metadata.py
> -            await save_directives(conn, dc)
these were intentionally removed as the hardcoded metadata was just for testing.

2022-02-07 12:38 UTC, haakondr commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
> -        },
this should probably not have been removed. @ZofiaRudjord ? also got removed in commit https://github.com/NIVANorge/odm2-postgres-api/commit/925941d731627b290e47853aef735398f118d1ea#diff-09a349c0efe69c877b2f62c0ee08e62a0df0b367b5cb7b6a7a876b9f75f581faL258

2022-02-07 12:38 UTC, haakondr commented on api/src/odm2_postgres_api/metadata_init/data/general/variables.py
> -    },
should not be deleted?

2022-02-07 12:38 UTC, haakondr commented on api/src/odm2_postgres_api/metadata_init/data/general/units.py
> -    },
should not be deleted?

2022-02-08 12:43 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/general/variables.py
> -    },
That should be in

2022-02-08 12:44 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
> -        },
@jemmima have you deleted it intensionally? (if so why?)

2022-02-08 12:44 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/general/units.py
> -    },
not deleted

2022-02-08 12:48 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
>          {
This also looks like deleted by accident

2022-02-08 12:49 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
>          {
should not have been deleted

2022-02-08 12:54 UTC, ZofiaRudjord requested changes
I looked through the PR and commented on the lines which were accidentally deleted and should be brought back.
There were several instances which showed differences caused by formatting. It is easy to overlook if sth was deleted for those cases.

2022-02-08 12:54 UTC, ZofiaRudjord commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
> -        },
should not have been deleted

2022-02-08 12:57 UTC, jemmima commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
> -        },
I've been trying to work out how this happened - I think it must have been a rebase error as I didn't remove any of these (intentionally), and I'm surprised to see them included in that commit, but it was the earliest commit included it the rebase so that is currently my best guess as the root cause.

2022-02-09 16:51 UTC, jemmima requested changes
I have odm2-postgres-api working now after reverting the directives table changes (for now) but I am having trouble running the tests. I have never got them working but we should validate they still work (ideally someone could help me :D)

2022-02-10 08:53 UTC, haakondr commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
> -        },
merge errors happen. In hindsight we should have done a better job to make sure our branch was "clean" before we started. From my experience things like this always happen when working with long-lived branches. 

The important thing is that we have a good overview before deploying to production.

2022-02-10 09:05 UTC, jemmima commented on api/src/odm2_postgres_api/db_init/ODM2_for_PostgreSQL.sql
> -alter table ODM2.Directives add column directivename varchar (255) UNIQUE;
Done in [bdee0ad](https://github.com/NIVANorge/odm2-postgres-api/pull/206/commits/bdee0ad702cf75e9002183186208e1d4f9c4f378)

2022-02-10 10:11 UTC, haakondr commented on api/src/odm2_postgres_api/schemas/schemas.py
> +    featuregeometry: constr(max_length=255) = None  # type: ignore
I removed this line in https://github.com/NIVANorge/odm2-postgres-api/pull/206/commits/d74f5ddb317215afe910ccc1be8cade5d156764f to make the tests pass. We should probably add inn location info at some time, but I suggest we sit down and discuss the API structure first

2022-02-10 14:59 UTC, jemmima commented on api/src/odm2_postgres_api/schemas/schemas.py
> +    featuregeometry: constr(max_length=255) = None  # type: ignore
I'm actually having trouble just running the tests locally - any ideas?: 

```test setup failed
self = <pytest_docker_compose.DockerComposePlugin object at 0x7fafd8627a60>
request = <SubRequest 'docker_project' for <Function test_post_new_indices>>

    @pytest.fixture(scope="session")
    def docker_project(self, request):
        """
        Builds the Docker project if necessary, once per session.
    
        Returns the project instance, which can be used to start and stop
        the Docker containers.
        """
    
        compose_files = []
    
        for docker_compose in [Path(f) for f in request.config.getoption("docker_compose").split(',')]:
            if docker_compose.is_dir():
                docker_compose /= "docker-compose.yml"
    
            if not docker_compose.is_file():
>               raise ValueError(
                    "Unable to find `{docker_compose}` "
                    "for integration tests.".format(
                        docker_compose=docker_compose.absolute(),
                    ),
                )
E               ValueError: Unable to find `/Users/jemmima/odm2/odm2-postgres-api/api/tests/docker-compose.yml` for integration tests.```

2022-02-10 15:31 UTC, jemmima reviewed
Getting the following error on a fresh environment:

```Attaching to odm2-postgres-api_odm2_postgres_api_1
odm2_postgres_api_1  | Traceback (most recent call last):
odm2_postgres_api_1  |   File "/app/src/odm2_postgres_api/main.py", line 21, in <module>
odm2_postgres_api_1  |     from odm2_postgres_api.app import app
odm2_postgres_api_1  | ModuleNotFoundError: No module named 'odm2_postgres_api'
```
I'm actually a bit stuck and confused about why it's not working locally for me but it is working in ci?

2022-02-11 18:10 UTC, jemmima commented
> Member

The image was not coming up locally or in nivatest since pip install command was removed from /api Dockerfile in dc23c9a72e4d9b7119d17aeb25560951623c5dc3. This meant the api code was not added to the module search path and api container was failing to come up. Fixed in [Fix local docker env](https://github.com/NIVANorge/odm2-postgres-api/pull/206/commits/89bdb19377251b692e79c9fba22632f79c5468c1)

2022-02-14 08:29 UTC, haakondr commented on api/src/odm2_postgres_api/schemas/schemas.py
> +    featuregeometry: constr(max_length=255) = None  # type: ignore
This has to do with your current working directory. You need to run the tests from api/ folder (and not tests folder).

The plugin used in odm2 API called `pytest-docker-compose` is not very flexible when it comes to defining the location of the docker-compose.yml file. This is the main reason I've not used this for kafka-sink (and observations-api)

2022-02-14 08:36 UTC, haakondr commented
> > Getting the following error on a fresh environment:
> > ```
> > odm2_postgres_api_1  | Traceback (most recent call last):
> > odm2_postgres_api_1  |   File "/app/src/odm2_postgres_api/main.py", line 21, in <module>
> > odm2_postgres_api_1  |     from odm2_postgres_api.app import app
> > odm2_postgres_api_1  | ModuleNotFoundError: No module named 'odm2_postgres_api'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm actually a bit stuck and confused about why it's not working locally for me but it is working in ci?
> 
> The image was not coming up locally or in nivatest since pip install command was removed from /api Dockerfile in [dc23c9a](https://github.com/NIVANorge/odm2-postgres-api/commit/dc23c9a72e4d9b7119d17aeb25560951623c5dc3). This meant the api code was not added to the module search path and api container was failing to come up. Fixed in [89bdb19](https://github.com/NIVANorge/odm2-postgres-api/commit/89bdb19377251b692e79c9fba22632f79c5468c1)

Ah, sorry about that. Not sure why we're doing this though. I must admit I've never fully understood how to handle relative paths for imports in python. 

The problem here is how do we define which file the following import points to:

```
from odm2_postgres_api.app import app
```

The way we've solved this in kafka-sink and observations-api is to move the entrypoint (main.py) one directory up, so that relative to main.py's directory python can look for the folder `odm2_postgres_api` and the file app.py.

The alternative solution which is done here is to do a pip install on the odm2_postgres_api folder and make all the files available as a module on the local python installation. This works and also allow us to put app.py in whatever location we want. 

One drawback to this is that we need to run `pip install .` for all code changes, or alternatively run `pip install -e .` which will cause changes to apply. This is not very difficult to do, but I've found the more commands you need to run, the higher the chance something gets wrong. Setting up virtual environments and handling that is enough trouble I think.

TLDR; i am not sure about what the best way to do this, but we should probably land on one way to do it.

2022-02-14 08:48 UTC, haakondr commented
I added back in code accidentally deleted in 7f1090f, hopefully everything should be ok now

2022-02-14 12:20 UTC, jemmima commented
@haakondr  did you mean to commit these secrets? https://github.com/NIVANorge/odm2-postgres-api/tree/dev/api/src/odm2_postgres_api/config

2022-02-17 09:51 UTC, haakondr commented
> @haakondr did you mean to commit these secrets? https://github.com/NIVANorge/odm2-postgres-api/tree/dev/api/src/odm2_postgres_api/config

These are used for local development so should not be a problem

2022-03-15 12:16 UTC, jemmima commented on api/src/odm2_postgres_api/metadata_init/data/mass_spec/mass_spec_metadata.py
>          {
I deleted this as we don't want not working algo versions

2022-03-15 12:53 UTC, jemmima approved these changes

2022-03-15 13:22 UTC, jemmima commented
> I looked through the PR and commented on the lines which were accidentally deleted and should be brought back. There were several instances which showed differences caused by formatting. It is easy to overlook if sth was deleted for those cases.

I have compared with how dev looked like before the kafka branch was merged, and I think everything is there. If something is missed it is not difficult to put back, but I have spent an hour going through the diffs and I feel confident enough given the risk is low.

2022-03-15 13:26 UTC, merged