Feature/create indices
NIVANorge/odm2-postgres-api pull request #55
Opened 2020-09-01 13:47 UTC by roryscot

Depends on https://github.com/NIVANorge/begroing-data-upload/issues/63

2020-09-02 06:42 UTC, haakondr requested changes
made a lot of nitpicky comments. Don't think we need to fix all of these, but I think the following needs to be fixed:

- type definition for stations/samplingfeatures
- remove dead code (get_index_names) if not used
- different http status code if method does not exist
- consider to refer to processinglevelcode etc by code instead of id
- improve endpoint so that it responds written values and assert this in the API test

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        await post_measurement_results(data_measurement_result, connection)
reusing the http methods here. There is probably nothing hindering from using them directly, but I think that we should strive to call them only over http to have a unified way in.

I suggest we either call core_queries.upsert_measurement_result directly or extract the functionality out to a shared function (currently it is only contains one code-line)

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +    return schemas.BegroingIndices(personid=user.personid, **new_index.dict())
Ideally I think we should return the object structure that was written to the database. In this case we try to reconstruct the same structure. If we return the returned objects from the sql queries then we can also add unit tests that test the response.

In this specific case I would improve upsert_measurement_result and return the written rows and build the BegroingIndices object

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            resulttypecv="Measurement",
note to self: would be great to publish a pypi package with ODM2 CV's as enums

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            processinglevelid=1,  # id:1, "processinglevelcode": "0", "definition": "Raw Data"
Maybe we should not refer to processinglevels as id but rather fetch processinglevelcode = '0'. I got confused here first and thought we were inserting code = 1, but we are really inserting id=1 which is processinglevelcode=0 (did not read comment, usually don't read them).

Problem with this approach is that it is very tightly coupled to metadata setup. What happens if we initialize a new database and forget to reset id sequences. Then the application breaks.

I think we need to fetch the processinglevelid for a given code and never refer to internal id's in our application. This is where ODM2 normalized structure has gone a bit too far IMO as this is quite cumbersome to work with.

Same goes for units above.

@RmStorm thoughts?

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            samplingfeatureuuid=new_index.station['samplingfeatureuuid'],
we should create a type definition for station

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        begindatetime=new_index.date,
I don't think we need to improve this now, but:

The UI posts dates in the following format:

```
2020-09-02T00:00:00.000Z
```

This contains timezone information (Z being UTC). The date coming in is in this case a timezone-aware date and we might as well just use the incoming datetime object to derive the utcoffset. I see that @RmStorm has created validations to check if specified offset matches actual offset, but maybe we can just derive all this?

this way we'd have less tightly coupling with the clientside. With current implementation the client HAS to use utc, and that is not documented anywhere

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        equipmentids=[],
are there any equipment used that should be stored within the ODM2 database? if yes, I think we should create issues in github for this

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            valuedatetimeutcoffset=0
What does the data structure for a index look like?

is it 1 value per begroing observation? Or an aggregate over time? Should be documented in https://github.com/NIVANorge/begroing-data-upload/issues/98

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +        #                     *categoricalresultvalues_data.values())
Also see that this is unused. Will it be used or can it be deleted?

2020-09-02 06:42 UTC, haakondr commented on tests/test_api.py
> +        "Niva-User": "eyJpZCI6IjEiLCJlbWFpbCI6ImJlZ3JvaW5nQGRldnVzZXIuY2…kaXNwbGF5TmFtZSI6IkFsZnJlZCBCZWdyb2luZyBPbHNlbiJ9"
for readability it is probably better to create a NivaPortUser object and base64 encode it:

```
b64encode(json.dumps(user_obj).encode('utf-8'))
```

We could look into adding some util functions to do this in the future.

2020-09-02 06:42 UTC, haakondr commented on tests/test_api.py
> +        response = client.post(url="/indices", data=json.dumps(index_data), headers=headers)
not really testing anything here. I think we need to assert the response that all values look ok. This relates to my comment about returning written values in the endpoint. 

If the endpoint returns the written values from sql as response we can assert on it here in the tests

2020-09-02 06:42 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                       niva_user: str = Header(None)):
Could use a docstring here describing what the endpoint does. From what I've understood:

``` 
"""
Stores a list of indices for observations on a given timestamp/station. One observation may have many indices.
"""
```

2020-09-02 10:47 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +        #                     *categoricalresultvalues_data.values())
hehe we were trying to get the number 30 included in a doc string so `pytest --fixtures` would give a nice informative doc string. It didn't work and this is a leftover from that attempt :laughing:

2020-09-02 10:48 UTC, RmStorm commented on tests/integration_test_fixtures.py
> +def try_db_init(tries=DEFAULT_TRIES):
hehe we were trying to get the number 30 included in a doc string so `pytest --fixtures` would give a nice informative doc string. It didn't work and this is a leftover from that attempt :laughing:

2020-09-02 10:51 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +            raise HTTPException(status_code=404, detail="Method not found.")
agreed!

2020-09-02 10:54 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            processinglevelid=1,  # id:1, "processinglevelcode": "0", "definition": "Raw Data"
Agreed when there is a unique code in a table we should use that instead of id!

2020-09-02 10:55 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            valuedatetimeutcoffset=0
hmm, I think aggregate over time.

2020-09-02 10:57 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +    return schemas.BegroingIndices(personid=user.personid, **new_index.dict())
yes, I think that can make sense. I didn't do it for the observations because I wanted to have something working. I think you're right though that both of these methods should return the actual database entries...

2020-09-02 11:14 UTC, haakondr commented on tests/integration_test_fixtures.py
> +def try_db_init(tries=DEFAULT_TRIES):
aha, I understand

2020-09-03 13:52 UTC, roryscot commented on src/odm2_postgres_api/queries/core_queries.py
> +            raise HTTPException(status_code=404, detail="Method not found.")
raise HTTPException(status_code=422, detail="Please specify valid methodcode.")
?

2020-09-03 14:05 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +            raise HTTPException(status_code=404, detail="Method not found.")
yep, that's fine. I am not sure whether this results in a json response or a text/html response. We'd probably want to use json response.

This does depend on whether there is a exceptionhandler for HTTPException that responds with json

2020-09-03 14:06 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +@router.post("/indices", response_model=schemas.BegroingIndices)
Since we split out begroing_routes into its own file, we should probably also reflect this in the url structure. I propose the following:

- POST /begroing/observations
- POST /begroing/indices

2020-09-03 17:07 UTC, roryscot commented on src/odm2_postgres_api/queries/core_queries.py
> +        #                     *categoricalresultvalues_data.values())
@RmStorm ?

2020-09-04 11:45 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +@router.post("/indices", response_model=schemas.BegroingIndices)
this endpoint is not transactional, as far as I can tell. This is important. Basically we'd want to wrap all this code with

```
    async with conn.transaction():
```

This way all writes are rolled back if something goes wrong

2020-09-04 12:41 UTC, haakondr commented on src/odm2_postgres_api/schemas/schemas.py
> +    projects: List[Directive]
I think we should validate that we have at least one item in our list. Currently empty list is valid.

It seems like this can be done with "conlist":

https://stackoverflow.com/questions/61468548/check-if-list-is-not-empty-with-pydantic-in-an-elegant-way

```
projects: conlist(Directive, min_items=1)
```

Have not tried this, just reading docs

2020-09-07 18:30 UTC, roryscot commented on src/odm2_postgres_api/routes/begroing_routes.py
> +@router.post("/indices", response_model=schemas.BegroingIndices)
Should we also do that with line 33: post_begroing_result ?

2020-09-07 18:44 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +@router.post("/indices", response_model=schemas.BegroingIndices)
Yes

2020-09-08 07:33 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +@router.post("/indices", response_model=schemas.BegroingIndices)
post begroing result already has this!

2020-09-15 14:19 UTC, roryscot commented
Did we want to do anything else before merging?

2020-09-16 16:19 UTC, merged