49 metadata setup
NIVANorge/odm2-postgres-api pull request #59
Opened 2020-09-07 12:41 UTC by haakondr

## core changes
- refactored the script so that sequence of execution is a bit more
readable. Slit metadata setup into different files
- trigger CV download as part of script
- added checks in endpoints if row exists, we do nothing
- dynamically setting niva org id in cases where it was hardcoded
  - wrap all metadata definitions as functions. This is used to pass in
props like niva org id, but do this for all to ensure consistency. Maybe
unnecessary (?) 
- validate metadata clientside with pydantic types before
posting
  - this enables us to do unittesting and easier validation of the 
structure
- moved begroing specific stuff to its own file

## misc changes

- moved db_init and config to its own folder
- differentiated cv create and response (cv create has CV_TABLE as part
of it). Could consider to move this to pathparam as well?

## TODOS

- may want to trigger CV download in a different way as it is quite
slow
-no way to update org, person, etc. as it is now. Only prevent
duplicates
- begroing method annotations set to [1]. What does that mean?

2020-09-07 14:28 UTC, haakondr commented on src/db_init/ODM2_for_PostgreSQL.sql
> +ALTER TABLE ODM2.units ADD UNIQUE (unitstypecv, unitsabbreviation);
there are probably more unique constraints that we can consider adding

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/app.py
> +    await populate_metadata(api_pool_manager.pool)
this is the big change, running this on app startup. This makes local dev much more pleasant, and is also automatically ran in test/prod. 

Does add some to app startup, but that is taken care of by rolling deployment.

downside to this approach is that we run this once per replica, so if we have many replicas there will be some load on our database during deployment but  I don't think this should be an issue. The setup should now be idempotent (I hope) so it can be ran many times

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/controlled_vocabularies/cv_definitions/cv_actiontype.json
> +{
ran my new script download.csv.py and stored results in this folder. This makes the workflow of populating with CV's much easier

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/controlled_vocabularies/cv_definitions/cv_actiontype.json
> +{
```
 du cv_definitions/ -sh
1020K	cv_definitions/
```

1mb of files. Not too much so I think this fits into git. 

I prettied them for readability but we can consider to not do that to minimize file size

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/controlled_vocabularies/download_cvs.py
> +CV_URL = "http://vocabulary.odm2.org/api/v1/%s/?format=json"
notice the undocumented "format=json" option

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/controlled_vocabularies/load_cvs.py
> +    async with db_pool.acquire() as conn:
acquiring just one connection and run things in sequence. Could perhaps be speed up by doing things async but did not bother rewriting

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/metadata_init/populate_metadata.py
> +    logging.info("ODM2 metadata init done")
this is the main script for populating metadata. Could be rewritten to async by using the db pool, but don't think there is a lot to save

2020-09-07 14:28 UTC, haakondr commented on src/odm2_postgres_api/metadata_init/repository.py
> +    return await core_queries.insert_method(connection, method)
took some of the API endpoints out. I don't think any of the API endpoints in shared_routes.py can be used in their current state so may consider to just remove them all?

2020-09-09 09:01 UTC, RmStorm commented on src/odm2_postgres_api/controlled_vocabularies/cv_definitions/cv_actiontype.json
> +{
prettifying adds minimal storage space and adds a ton of readability so having them be pretty is definitely the way to go.

2020-09-09 09:06 UTC, RmStorm commented on src/odm2_postgres_api/controlled_vocabularies/download_cvs.py
> +    loop = asyncio.get_event_loop()
I don't think you need to explicitly get the loop. The preferred way to do this since (3.6? 3.7?) is to simply call 
```asyncio.run(main())```

2020-09-09 09:09 UTC, RmStorm commented on src/odm2_postgres_api/controlled_vocabularies/load_cvs.py
> +            cvs = read_cv_from_file(cv_name)
maybe `cvs` here can be renamed to `cv_entries`?

2020-09-09 09:12 UTC, RmStorm commented on src/odm2_postgres_api/main.py
> +            env_file = Path(__file__).parent.parent / 'config' / 'localdocker.env'
`Path(__file__).parent.parent` == `Path(__file__).parents[1]`
The second notation has my prefence :sweat_smile:

2020-09-09 13:08 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +    logging.info(f"Inserting row", extra={"table": table_name})
maybe .debug?

2020-09-09 13:10 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_organization(conn: asyncpg.connection, org_code: str) -> Optional[Organizations]:
This one fits in find_row right?

2020-09-10 05:28 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_organization(conn: asyncpg.connection, org_code: str) -> Optional[Organizations]:
hmm, yes. Think I wrote it before I wrote generic function find_row

2020-09-10 11:58 UTC, haakondr commented on src/odm2_postgres_api/controlled_vocabularies/download_cvs.py
> +    loop = asyncio.get_event_loop()
yep that worked. thanks

2020-09-10 11:59 UTC, haakondr commented on src/odm2_postgres_api/main.py
> +            env_file = Path(__file__).parent.parent / 'config' / 'localdocker.env'
moved config back into its original location so this is no longer needed

2020-09-10 12:00 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_organization(conn: asyncpg.connection, org_code: str) -> Optional[Organizations]:
I see that this one is actually not in use anymore. I wrote it initially, then made find_row and forgot to delete this

2020-09-10 12:00 UTC, haakondr commented
made a commit with PR feedback, should be all done now I think

2020-09-10 14:23 UTC, RmStorm requested changes
I think this is in principle good to go there is just two things.

1. The tests should pass. we can probably just set sensible defaults in the the integration test fixtures.
2. I'm not sure we should remove all these endpoints in `shared_routes.py` I agree that in the future they *might* be replaced by something else but for now they connect to the queries and I think should just be left in place? We're going to have to build some sort of interface for managing that kind of metadata and then we will have to recreate these endpoints?

2020-09-10 14:44 UTC, RmStorm commented
Also, can we rename the file `repository.py` to something more informative? There is a bunch of functions in there that are basically idempotent wrappers for `core_queries.py` as far as I can tell. I don't really have a good suggestion though..  `idempotent_core_helpers.py` maybe? :rofl:

2020-09-11 09:14 UTC, haakondr commented
> core_queries

renamed it "storage". What do you think?

```
from storage import save_organisation
```

2020-09-11 09:34 UTC, RmStorm approved these changes
Looks great. Makes it much more usable. We should keep in mind to re-evaluate this in the future once the metadata becomes fully managed by the database.

2020-09-11 09:34 UTC, merged