API endpoint for storing rfid_fish observations
NIVANorge/odm2-postgres-api pull request #62
Opened 2020-09-09 10:06 UTC by haakondr

issue https://github.com/NIVANorge/fish_rfid/issues/1

Changes:

- new endpoint POST /fish-rfid/observation (requires niva-user to be
set)

stores observations as actions with methodcode fish_rfid:observe_fish
links action to station and fish: action -> 2 featureactions -> 2
samplingfeatures (fish+station)

I am not storing actionby as currently we only have the user information
of the user who created the API token. Would perhaps be misleading to
store this as action_by, see TODO below.

- initial metadatasetup for fish_rfid

hardcodes one station, awaiting details from @Pit-Fish (Erik), will
update once we have them.

defines methods for registering fish attributes and sensor observing
fish

- changed ActionsCreate to take a list of action_by
  - this way, action_by is optional but also supports many action_by's
storing observations as

TODOS:

- pass along API tokens linked with equipment from niva-port:
https://github.com/NIVANorge/niva-port/issues/226

2020-09-09 10:15 UTC, haakondr commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +            "featuregeometrywkt": "POINT (10.907013757789976 60.25819134332953)",
fill in values from https://github.com/NIVANorge/fish_rfid/issues/5

2020-09-09 10:15 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +            action_by_rows.append(action_by_row)
currently I am not storing "who" did it. Slightly awkward to try to fit these data into the data model but I think it sort of works.

2020-09-09 10:15 UTC, haakondr commented on src/odm2_postgres_api/schemas/schemas.py
> +    # relatedsamplingfeatures: List[Tuple[int, str]] = []
@RmStorm I had trouble storing SamplingFeaturesCreate with this being set. Not sure what the best solution is, either create a function similar to do_action or omit this

2020-09-09 10:15 UTC, haakondr commented on tests/test_fish_rfid.py
> +        consecutive_detections=19,
I am currently not storing field_strength and consecutive_detections.

I am using the duration to calculate the action endtime. Could consider to store the duration directly but thought this maybe made sense..

2020-09-09 10:15 UTC, haakondr commented on tests/test_fish_rfid.py
> +"""
copy pasted this subset of the oregon output. Not sure what the best testing workflow would be, but thought it could make sense to have some format we use to copy paste the raw output (more or less, I omitted some noise)

2020-09-09 10:19 UTC, haakondr commented
## example request

```
{
  "observations": [
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:03:33.800000",
      "station_code": "AAA",
      "duration": 0.9,
      "field_strength": 0.2,
      "consecutive_detections": 10
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:04:04.100000",
      "station_code": "AAA",
      "duration": 1.5,
      "field_strength": 0.2,
      "consecutive_detections": 16
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:04:06.600000",
      "station_code": "AAA",
      "duration": 1.6,
      "field_strength": 0.2,
      "consecutive_detections": 17
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:04:09.200000",
      "station_code": "AAA",
      "duration": 1.7,
      "field_strength": 0.2,
      "consecutive_detections": 18
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:04:12",
      "station_code": "AAA",
      "duration": 2.0,
      "field_strength": 0.2,
      "consecutive_detections": 21
    },
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:34:24.100000",
      "station_code": "AAA",
      "duration": 0.8,
      "field_strength": 0.2,
      "consecutive_detections": 9
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:51:57.600000",
      "station_code": "AAA",
      "duration": 1.0,
      "field_strength": 0.2,
      "consecutive_detections": 11
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:01",
      "station_code": "AAA",
      "duration": 1.2,
      "field_strength": 0.2,
      "consecutive_detections": 13
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:06.200000",
      "station_code": "AAA",
      "duration": 2.2,
      "field_strength": 0.2,
      "consecutive_detections": 23
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:11",
      "station_code": "AAA",
      "duration": 2.4,
      "field_strength": 0.2,
      "consecutive_detections": 25
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:16.300000",
      "station_code": "AAA",
      "duration": 1.8,
      "field_strength": 0.2,
      "consecutive_detections": 19
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:21.100000",
      "station_code": "AAA",
      "duration": 2.3,
      "field_strength": 0.2,
      "consecutive_detections": 24
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:25.800000",
      "station_code": "AAA",
      "duration": 3.3,
      "field_strength": 0.2,
      "consecutive_detections": 34
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:27.500000",
      "station_code": "AAA",
      "duration": 4.1,
      "field_strength": 0.2,
      "consecutive_detections": 42
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:35.300000",
      "station_code": "AAA",
      "duration": 2.1,
      "field_strength": 0.2,
      "consecutive_detections": 22
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:37.600000",
      "station_code": "AAA",
      "duration": 1.8,
      "field_strength": 0.2,
      "consecutive_detections": 23
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:39.800000",
      "station_code": "AAA",
      "duration": 1.5,
      "field_strength": 0.2,
      "consecutive_detections": 16
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:41.900000",
      "station_code": "AAA",
      "duration": 0.9,
      "field_strength": 0.2,
      "consecutive_detections": 10
    },
    {
      "fish_tag": "982_000199951389",
      "datetime": "2020-06-08T14:52:46.700000",
      "station_code": "AAA",
      "duration": 1.1,
      "field_strength": 0.2,
      "consecutive_detections": 12
    },
    {
      "fish_tag": "982_000356452118",
      "datetime": "2020-06-08T14:52:48.700000",
      "station_code": "AAA",
      "duration": 1.1,
      "field_strength": 0.2,
      "consecutive_detections": 16
    },
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:55:02.400000",
      "station_code": "AAA",
      "duration": 0.7,
      "field_strength": 0.2,
      "consecutive_detections": 8
    },
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:55:06.400000",
      "station_code": "AAA",
      "duration": 0.9,
      "field_strength": 0.5,
      "consecutive_detections": 10
    },
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:55:14",
      "station_code": "AAA",
      "duration": 0.9,
      "field_strength": 0.5,
      "consecutive_detections": 10
    },
    {
      "fish_tag": "0000_000174764644",
      "datetime": "2020-06-08T14:55:18.600000",
      "station_code": "AAA",
      "duration": 0.9,
      "field_strength": 0.5,
      "consecutive_detections": 10
    }
  ]
}
```

## example response

```
{
  "observations": [
    {
      "action": {
        "enddatetimeutcoffset": 0,
        "enddatetime": "2020-06-08T14:03:34.700000",
        "begindatetimeutcoffset": 0,
        "begindatetime": "2020-06-08T14:03:33.800000",
        "action_by": [],
        "actiontypecv": "Observation",
        "methodcode": "fish_rfid:observe_fish",
        "actiondescription": null,
        "actionfilelink": null,
        "equipmentids": [],
        "directiveids": [],
        "relatedactions": [],
        "actionid": 223
      },
      "fish_sampling_feature": {
        "samplingfeatureuuid": "ab38bfa8-bf08-46cb-ad60-589701fb7638",
        "samplingfeaturetypecv": "Specimen",
        "samplingfeaturecode": "0000_000174764644",
        "samplingfeaturename": null,
        "samplingfeaturedescription": null,
        "samplingfeaturegeotypecv": null,
        "featuregeometrywkt": null,
        "elevation_m": null,
        "elevationdatumcv": null,
        "samplingfeatureid": 52
      },
      "station_sampling_feature": {
        "samplingfeatureuuid": "49c799ba-f1df-11ea-9179-ffcbac9423dd",
        "samplingfeaturetypecv": "Site",
        "samplingfeaturecode": "AAA",
        "samplingfeaturename": "fish rfid station",
        "samplingfeaturedescription": "Station detecting tagged nearby tagged fish with Oregon RFID sensors",
        "samplingfeaturegeotypecv": "Point",
        "featuregeometrywkt": "POINT (10.907013757789976 60.25819134332953)",
        "elevation_m": null,
        "elevationdatumcv": null,
        "samplingfeatureid": 51
      }
    },
    {
      "action": {
        "enddatetimeutcoffset": 0,
        "enddatetime": "2020-06-08T14:04:05.600000",
        "begindatetimeutcoffset": 0,
        "begindatetime": "2020-06-08T14:04:04.100000",
        "action_by": [],
        "actiontypecv": "Observation",
        "methodcode": "fish_rfid:observe_fish",
        "actiondescription": null,
        "actionfilelink": null,
        "equipmentids": [],
        "directiveids": [],
        "relatedactions": [],
        "actionid": 224
      },
      "fish_sampling_feature": {
        "samplingfeatureuuid": "f2ba9c1f-e3f3-4757-bb36-1f679de7271a",
        "samplingfeaturetypecv": "Specimen",
        "samplingfeaturecode": "982_000199951389",
        "samplingfeaturename": null,
        "samplingfeaturedescription": null,
        "samplingfeaturegeotypecv": null,
        "featuregeometrywkt": null,
        "elevation_m": null,
        "elevationdatumcv": null,
        "samplingfeatureid": 53
      },
      "station_sampling_feature": {
        "samplingfeatureuuid": "49c799ba-f1df-11ea-9179-ffcbac9423dd",
        "samplingfeaturetypecv": "Site",
        "samplingfeaturecode": "AAA",
        "samplingfeaturename": "fish rfid station",
        "sa [...]

2020-09-09 10:21 UTC, haakondr commented
Looking at the example response, I may want to normalize this a bit, as it is perhaps not that interesting to respond station/fish sampling feature PER observation.

Maybe something like the following would fit as response:

station_sampling_features: []
fish_sampling_features: []
actions: []

2020-09-10 12:27 UTC, haakondr commented
Some quick testing on the request payload size. Tried with a large-ish list of observations (292) and small (fish_small) with 24 observations:

```
cat fish.json | jq ".observations | length"
292

# think i forgot one line of observations
cat fish.csv | wc -l
291

gzip -k fish*
bzip -zk fish*

du fish* -sh
24K	fish.csv
4,0K	fish.csv.gz
52K	fish.json
4,0K	fish.json.bz2
4,0K	fish.json.gz
4,0K	fish_small.csv
4,0K	fish_small.csv.gz
4,0K	fish_small.json
4,0K	fish_small.json.bz2
4,0K	fish_small.json.gz

```
So, seems like there is a baseline of 4kb and request size will not grow significantly above that. I guess it will grow some per station/fish tag type but that is unavoidable I think.

Also compared with csv and seems to be the same size. Pros of csv is that it is the same size without using gzip, but I think json adds so much more flexibilty and readability

2020-09-10 14:33 UTC, RmStorm commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +            "methodlink": "https://github.com/NIVANorge/fish_rfid/",
I think this link should link to a specific and small document outlining the procedure (fishing technology used, workflow for measuring and tagging, and so on. Not just the repo.

2020-09-10 14:39 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +            action_by_rows.append(action_by_row)
I think we only need the returned rows if we want to return the bridge_id's if we don't need to return these we can simplify this.

2020-09-10 14:48 UTC, RmStorm commented on src/odm2_postgres_api/schemas/schemas.py
> +    action_by: List[ActionsByFields] = []
I think the item here should be `ActionsBy` or `ActionsByCreate`. Not `ActionsByFields` since it leaves out the `action_id`.

2020-09-10 14:54 UTC, RmStorm commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_repository.py
> +        fa_station = await create_feature_action(conn, FeatureActionsCreate(
The station should definitely be preregistered right? Although this is quite practical ^^

2020-09-10 14:58 UTC, RmStorm commented on src/odm2_postgres_api/schemas/schemas.py
> +    action_by: List[ActionsByFields] = []
Ah, I see. We need to create an intermediate abstraction so that we can use `action_by` as `ActionsByFields` in `ActionsCreate` and as `ActionsBy` in `Action`

2020-09-11 11:48 UTC, haakondr commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +            "featuregeometrywkt": "POINT (10.907013757789976 60.25819134332953)",
james knows. Need Erik who works with the sensors to define station name and tell us where it is

2020-09-14 11:23 UTC, haakondr commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_repository.py
> +        fa_station = await create_feature_action(conn, FeatureActionsCreate(
station needs to be preregistered, yes. Fish sampling feature does not

2020-09-18 10:19 UTC, RmStorm requested changes
Hi @haakondr I made a couple comments and I think the changes to the tests are most important. It will make testing much easier if we implement a async rollback fixture!

2020-09-18 10:19 UTC, RmStorm commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_routes.py
> +        user = await create_or_get_user(conn, niva_user)
I think create_or_get_user can be called outside the transaction but it's not that important.

2020-09-18 10:19 UTC, RmStorm commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_repository.py
> +        if station_sf not in station_sampling_features:
shouldn't we `raise` on `None`. We don't have run time checking right? This code passes the linter since the return type of find_row is unknown.

2020-09-18 10:19 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_or_create_sampling_feature(conn, code: str, sf_type: str, wkt: str = None) -> SamplingFeatures:
It feel like this should have an input signature of `(conn, new_sf = SamplingFeaturesCreate)` but that can't work because the uuid is likely unknown client side. Should we leave the signature as is or create a SFQuery schema that lacks uuid?... I think leaving it as is is fine but I still wanted to share my thoughts on it to ask you @haakondr.

2020-09-18 10:19 UTC, RmStorm commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +        # {
If we don't add a station this code should be removed IMO.

2020-09-18 10:19 UTC, RmStorm commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +            "methodlink": "https://github.com/NIVANorge/fish_rfid/",
I still think we should create two .md documents in the repo to describe the two methods.

2020-09-18 10:19 UTC, RmStorm commented on tests/test_fish_rfid.py
> +async def test_store_fish_observations(wait_for_db, clear_db):
we should use async fixtures that open and rollback a transaction as discussed. That's a lot more solid for a testing regime.

2020-09-18 10:47 UTC, haakondr commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_routes.py
> +        user = await create_or_get_user(conn, niva_user)
are there any performance or other arguments for doing that?

2020-09-18 10:51 UTC, haakondr commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_repository.py
> +        if station_sf not in station_sampling_features:
you are right. Maybe we should have a variant of find_row which raises exception?

What would be the best:

- a different function: get_row that behaves like find_row except raises exception on None?
- a boolean parameter raise_on_errors find_row(...., raise_on_errors=True)?

2020-09-18 10:52 UTC, haakondr commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_or_create_sampling_feature(conn, code: str, sf_type: str, wkt: str = None) -> SamplingFeatures:
hmm. If we intend to expose this directly in the API, then I think it makes sense to create a separate type for it. Maybe also with its current usage, but I don't know..

2020-09-18 10:53 UTC, haakondr commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +        # {
It is intended to be added once Erik responds with the exact location. I could of course leave it out entirely

2020-09-18 11:12 UTC, haakondr commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_repository.py
> +        if station_sf not in station_sampling_features:
alright. I went for the 2nd option:

```
async def find_row(conn: asyncpg.connection, table: str, id_column: str, identifier, model, raise_if_none=False):
    row = await conn.fetchrow(f"SELECT * FROM {table} WHERE {id_column}=$1", identifier)
    if row is None and raise_if_none:
        raise HTTPException(status_code=422, detail=f"did not find item in table {table} with id={identifier}")
    return model(**row) if row else None
```

2020-09-21 11:49 UTC, RmStorm commented on src/odm2_postgres_api/metadata_init/data/fish_rfid/fish_rfid_metadata.py
> +        # {
ok, leaving it in as a comment is fine then I guess.

2020-09-21 11:51 UTC, RmStorm commented on src/odm2_postgres_api/queries/core_queries.py
> +async def find_or_create_sampling_feature(conn, code: str, sf_type: str, wkt: str = None) -> SamplingFeatures:
Since it's not exposed let's leave it as is for now. It's simple and readable in it's current form which is off course :+1:

2020-09-21 11:54 UTC, RmStorm commented on src/odm2_postgres_api/routes/fish_rfid/fish_rfid_routes.py
> +        user = await create_or_get_user(conn, niva_user)
I guess not :see_no_evil:.

2020-09-21 12:03 UTC, merged