Reworked tests with rollback during test teardown
NIVANorge/odm2-postgres-api pull request #68
Opened 2020-09-22 07:22 UTC by haakondr

- created a new function scoped fixture "db_conn" that sets up a db
connection, starts a transaction and rollbacks during test teardown

- Refactored tests to not use dbpool and acquire connection but inject
it via the fixture

This speeds up tests by quite a lot as we no longer need to clear the db
tables.

TODO: I struggled with setting up init_metadata as a separate async
fixture as it relies on pytest-asyncio function scoped fixture
event_loop. I tried following the approach suggested at
https://github.com/pytest-dev/pytest-asyncio/issues/75 but did not
manage to "override" the fixture. Solved the issue by invoking
init_metadata within wait_for_db. Could perhaps rename this fixture, but
I think that ideally init_metadata is invoked as a separate fixture

TODO: In all our tests I have to explicitly import wait_for_db even
though db_conn is invoking it. Feels like I should not need to do this..

@RmStorm unrelated change/problem, but thought I'd also have a look at this now. When I invoke tests via pycharm the working directory is ./tests and then the pytest.ini addopts fail as it tries to find ./tests/tests/integration-test-docker-compose.yml. Is there a easy way to solve this within pytest-docker-compose?

2020-09-22 07:24 UTC, haakondr commented on tests/integration_test_fixtures.py
> +    asyncio.run(init_metadata())
I did not get the solution of redefining event_loop fixture to work so this is my workaround

2020-09-22 07:24 UTC, haakondr commented on tests/test_db.py
> +from integration_test_fixtures import db_conn, wait_for_db
I have to explicitly import wait_for_db even though db_conn fixture should invoke it. Am I doing something wrong?

2020-09-22 07:24 UTC, haakondr commented on tests/test_db.py
> +    person = await create_or_get_user(db_conn, b64encode(json.dumps(user_obj).encode('utf-8')))
probably a good idea to ignore whitespace as I did a lot of re-indenting

2020-09-24 11:36 UTC, RmStorm commented on tests/test_db.py
> +from integration_test_fixtures import db_conn, wait_for_db
I'm not quite sure what is going on. integration_test_fixtures is not automatically imported by pytest I guess. Only the file `conftest.py` is automatically imported so that is where pytest expects fixtures.

What is so strange about it that running: `pytest --fixtures` does list the fixtures available in integration_test_fixtures...

2020-09-24 11:45 UTC, RmStorm commented on tests/integration_test_fixtures.py
> +        await transaction.rollback()
if an error happens in a test the rollback is not triggered, I think it should work like so:
```python
async with conn.transaction() as transaction:
    yield conn
    await transaction.rollback()
```
ugh except that it doesn't because the contextmanager doesn't return the transaction. I will make an issue in the asyncpg repo for it...

That means it has to be like so:
```python
transaction = conn.transaction()
await transaction.start()
try:
    yield conn
finally:
    await transaction.rollback()
```

2020-09-24 11:45 UTC, RmStorm commented on tests/integration_test_fixtures.py
> +    asyncio.run(init_metadata())
This works just fine.

2020-09-24 11:46 UTC, RmStorm requested changes
I made some comments, currently the transactions is not always rolled back. If that is fixed it's good to go.

2020-09-24 11:49 UTC, haakondr commented on tests/integration_test_fixtures.py
> +        await transaction.rollback()
yeah that's how I originally had it, not sure why I changed it back without the try/finally, but we definitely need that, yes

2020-09-24 12:20 UTC, RmStorm approved these changes
This looks great. Let's merge.

2020-09-24 17:28 UTC, merged