Added register_replicas, register_sample and register_site end-points.
NIVANorge/odm2-postgres-api pull request #72
Opened 2020-09-23 12:39 UTC by ZofiaRudjord

Modified schemas as needed.

2020-09-28 10:23 UTC, RmStorm requested changes
I have some minor comments but especially the doc strings are important. I will give some additional thought to the affiliationid since a solution is not immediately obvious I think.

2020-09-28 10:23 UTC, RmStorm commented on src/odm2_postgres_api/routes/mass_spectrometry_routes.py
> +                                                   actiontypecv="Specimen analysis", methodcode="create_ms_data",
Can we prefix all methodcodes associated with mass-spec with either `ms_` or `mass_spec_`

2020-09-29 11:36 UTC, ZofiaRudjord commented on src/odm2_postgres_api/routes/mass_spectrometry_routes.py
> +    async with connection.transaction():
Done!

2020-09-29 11:38 UTC, ZofiaRudjord commented on src/odm2_postgres_api/routes/mass_spectrometry_routes.py
> +                                                   actiontypecv="Specimen analysis", methodcode="create_ms_data",
done!

2020-09-29 11:39 UTC, ZofiaRudjord commented on src/odm2_postgres_api/routes/mass_spectrometry_routes.py
> +                                                        affiliationid=1, isactionlead=True,
Agree. This will be fixed once we proceed to front end part.

2020-09-29 11:42 UTC, ZofiaRudjord commented on src/odm2_postgres_api/routes/mass_spectrometry_routes.py
> +                                                     annotationtypecv="Result annotation", annotationcode="raw",
I prefer to keep codes as encoded info. Result itself provides context and description.

2020-09-29 13:55 UTC, RmStorm approved these changes
This looks good. I will squash and merge and write a commit message explaining exactly what we have done here.

2020-09-29 13:58 UTC, merged