added test for POST /begroing/begroing_result
NIVANorge/odm2-postgres-api pull request #75
Opened 2020-09-30 09:27 UTC by haakondr

- had to fix a lot of hardcoded unit and variable id's. I am not very
happy about the amount of fetching that needs to be done. We should
consider adding some additional abstraction layers or perhaps write more
complex queries with nested queries? not sure what is best..

- mocking out aquamonitor writing. Checking that we call it if
WRITE_TO_AQUAMONTIOR=true

2020-10-05 10:39 UTC, RmStorm commented
>     * had to fix a lot of hardcoded unit and variable id's. I am not very
>       happy about the amount of fetching that needs to be done. We should
>       consider adding some additional abstraction layers or perhaps write more
>       complex queries with nested queries? not sure what is best..
> 
> 
> TODO: for some reason the mocking did not work and it called the actual implementation.
> 
> Another yet awkward thing is that I added aquamonitor credentials for running integration tests, BUT this test did also call aquamonitor to write as my mocking did not work which resulted in a write. I have cleaned up now, but removed the aquamonitor writing as part of test. Need to isolate this better and ideally get a read only user for integration tests.

A read only user is an excellent plan. Is that easy to do @roarbra?

2020-10-05 11:02 UTC, RmStorm requested changes
I think there is some inconsistencies in your local copy of ODM2, you should wipe and rerun it. Do you want to wait with merging this until you have refactored the frontend? I'm also ok with merging it directly after fixing the errors.

2020-10-05 11:02 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                    variableid=variable.variableid,  # This variable indicates the abundance of the taxon of the result
The comment can be removed if `variable` is renamed to `abundance_variable`.

2020-10-05 11:02 UTC, RmStorm commented on tests/test_begroing.py
> +user_header = "eyJpZCI6IDIyMSwgInVpZCI6ICIxZWQyMDBkMy1mMDlhLTQxNjQtOTExMC1hMWYyNGY4OTliYjMiLCAiZGlzcGxheU5hbWUiOiAiXHUwMGM1Z2UgT2xzZW4iLCAiZW1haWwiOiAiZGV2dXNlckBzb21lZW1haWwuY29tIiwgInByb3ZpZGVyIjog
Can we completely capitalize global hardcoded variables like these? like so: `USER_HEADER`

2020-10-05 11:08 UTC, haakondr commented
made issue about creating read only aquamonitor API user: https://github.com/NIVANorge/AquaMonitor/issues/22

2020-10-05 11:34 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                                                                  unitsname="Kiselalger Relative abundance"),
you are right. Rebuilt now and it looks as you describe.

Food for thought: we risk this happening quite a bit, and by describing units/variables etc as database rows, we need a good regime for keeping everyone up to date.

2020-10-05 11:42 UTC, merged

2020-10-07 07:45 UTC, roarbra commented
> 
> A read only user is an excellent plan. Is that easy to do @roarbra?

@RmStorm That could be solved by an Internal user, for instance your own user. Such a user will have full read access, but write access only to those projects that he has editing rights for. It's a little bit more job to introduce a test user, because we have a job that wipes out all Internal usernames that isn't within Active Directory.