Fetch begroing data
NIVANorge/odm2-postgres-api pull request #92
Opened 2020-10-26 12:58 UTC by haakondr

2020-10-26 13:03 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                    resultdatetimeutcoffset=0,
utcoffset is already validated to match 0, right @RmStorm ?

2020-10-26 13:03 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                    resultdatetimeutcoffset=0,
added this so that time is also stored on results

2020-10-26 13:03 UTC, haakondr commented on src/odm2_postgres_api/schemas/schemas.py
> +    value: str
this is somewhat duplicate of the other types. We already have BegroingObservations type which is used by the write endpoint when posting to aquamonitor API. I plan on refactoring this so that we use the same type.

This one is fully denormalized and I think that is the most flexible data model

2020-10-26 13:03 UTC, haakondr commented on tests/test_begroing.py
> +    taxa_create = [generate_taxon() for i in range(0, 3)]
I was planning on writing some helper functions for posting data so that we can split the tests for the GET endpoint into separate tests, but have not done that yet

2020-10-26 13:06 UTC, haakondr commented on src/odm2_postgres_api/queries/begroing_queries.py
> +    r.resultdatetime<=$4
I am not checking that utcoffset is matching. Not sure how to best do this. I think the whole concept of having utcoffsets as separate columns is very cumbersome. 

Yes, I get that odm2 wants to be db agnostic

2020-10-26 13:44 UTC, RmStorm commented on src/odm2_postgres_api/queries/begroing_queries.py
> +    r.resultdatetime<=$4
I agree, I'm not too sure what to do about it though.

2020-10-26 14:27 UTC, RmStorm requested changes
Looks great! Currently there is a linter issue that has to be fixed (see first comment). In addition to that I made commented with some minor nitpickings. These other comments you can ignore if you prefer it the way it currently is.

2020-10-26 14:27 UTC, RmStorm commented on src/odm2_postgres_api/queries/begroing_queries.py
> +    sampling_feature: uuid,
This variable should be called something else, maybe `sampling_feature_uuid`. Otherwise mypy will complain about redeclaration on line 35. Also `uuid` is not a valid type. Should be `uuid.UUID`.

2020-10-26 14:27 UTC, RmStorm commented on src/odm2_postgres_api/queries/begroing_queries.py
> +    def observations_from_row(station: SamplingFeatures, project: Directive, row: Dict) -> BegroingObservation:
I don't think this function should be nested. Also (just a preference), I like this a little better :see_no_evil: :
```python
def observations_from_row(station: SamplingFeatures, project: Directive, row: Dict) -> BegroingObservation:
    return BegroingObservation(
        project=project,
        station=station,
        timestamp=row["resultdatetime"],
        taxon=TaxonomicClassifier(**row),
        method=Methods(**row),
        value=row["categorical_value"] or str(row["measurement_value"])
    )
```

2020-10-26 14:27 UTC, RmStorm commented on src/odm2_postgres_api/queries/begroing_queries.py
> +         full outer join measurementresultvalues mrv on mrv.resultid = r.resultid
I think these should be left joins? instead of full outer joins?

2020-10-26 14:27 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +    user = await create_or_get_user(connection, niva_user)
middleware is a nice idea! I also think we can be quite verbose with logging. We can always later change statements to debug or remove them when we have more traffic.

2020-10-26 14:27 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +                    resultdatetimeutcoffset=0,
yes, looks good.

2020-10-26 14:27 UTC, RmStorm commented on tests/test_begroing.py
> +        **{
the intermediate dict seems a little unnecessary? is there some gotcha with using keywords directly on the pydantic object?

2020-10-27 13:59 UTC, haakondr commented on src/odm2_postgres_api/queries/begroing_queries.py
> +         full outer join measurementresultvalues mrv on mrv.resultid = r.resultid
yes you are right

2020-10-27 14:01 UTC, haakondr commented on tests/test_begroing.py
> +        **{
hm. I think I thought it was easier to read by defining it as dicts

2020-10-27 14:03 UTC, haakondr commented
@RmStorm I have made some changes, added a csv endpoint and a function that constructs a csv file from the list of observations.

This mapping is not 100%, but I would like to get some feedback at this stage. For instance, I am setting flag to "Less than" instead of ">"

2020-10-29 07:45 UTC, RmStorm requested changes
I know it's just in a test but using mutables as default values is asking for trouble! Otherwise this looks great.

2020-10-29 07:45 UTC, RmStorm commented on tests/testdata_builders.py
> +def default_method(overrides: Dict = {}) -> Methods:
It is very bad practice to use a mutable value as default argument! It is only declared once at the function declaration not once per function invocation. This means that all function calls have access to the same mutable object!

2020-10-29 07:45 UTC, RmStorm commented on src/odm2_postgres_api/schemas/schemas.py
> +    def validate_flag(cls, values):
good catch!

2020-10-29 07:48 UTC, RmStorm commented on tests/test_begroing.py
> +        **{
Completely fine by me!

2020-10-29 08:54 UTC, haakondr commented on tests/testdata_builders.py
> +def default_method(overrides: Dict = {}) -> Methods:
hm. you are right.

How would I do this then? I'd like to declare a default value as an empty object

2020-10-29 08:56 UTC, haakondr commented on tests/testdata_builders.py
> +def default_method(overrides: Dict = {}) -> Methods:
should I set default=None and then do this?

```
o = overrides or {}
Methods(**{**default, **o})
```

2020-10-29 10:17 UTC, RmStorm commented on tests/testdata_builders.py
> +def default_method(overrides: Dict = {}) -> Methods:
yes, defaulting to None and using a ternary is typical.
``` python
o = {} if overrides is None else overrides
```
This is a little more certain in case overrides is supplied but falsy.

2021-01-20 07:24 UTC, haakondr commented
Closing PR. While I put quite a lot of work into this, I don't think this is the way

2021-01-20 07:24 UTC, closed without merging