Update to tabluar format
NIVANorge/odm2-postgres-api pull request #96
Opened 2020-10-29 14:54 UTC by roryscot

Change backend to fit with new format: https://github.com/NIVANorge/begroing-data-upload/issues/148

2020-11-02 09:16 UTC, haakondr approved these changes
Looks good I think. I think the if check for truthy values needs to be considered. Could be ok, but not sure

2020-11-02 09:16 UTC, haakondr commented on src/odm2_postgres_api/schemas/schemas.py
> +    nEQR: Optional[float]
are all these values optional in all cases? Or is it like, if EQR is set, nEQR should also be set?

2020-11-02 09:16 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        for suffix in new_values:
This can be rewritten to a oneliner:

```
for prefix, new_values in new_indices.indices.items():
  ...
```

2020-11-02 09:16 UTC, haakondr commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            if value:
this if-check is truthy, so I think if value is 0 then the if check is false. Perhaps not what we want?

2020-11-02 09:16 UTC, haakondr commented on src/odm2_postgres_api/schemas/schemas.py
> +from mypy.suggestions import TypedDict
unused import. I think if we'd use TypedDict, we'd use the following import:

```
from typing import TypedDict
```

2020-11-03 20:31 UTC, roryscot commented on src/odm2_postgres_api/schemas/schemas.py
> +    nEQR: Optional[float]
Optional in all cases, as far as I know.

2020-11-10 13:38 UTC, RmStorm requested changes
Hey Rory, sorry for the delayed review. There are three problems with the code as is. I think the schemas should really derive from pydantic `BaseModel` instead of from `Dict` since this is what fastApi expects afaik. Also, the test is broken since a variable was changed from dict to tuple. The test should be fixed. Lastly, the post index endpoint must be wrapped in a transaction!

2020-11-10 13:38 UTC, RmStorm commented on tests/test_begroing.py
> +    index_data = (
The old `index_data` was a dict while this a tuple. This breaks the next line! This should remain a dict.

2020-11-10 13:38 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        for suffix in new_values:
Yeah, if these submodels are `Dict` you can do it like that:
```python
    for prefix, indexing_unit in beg_thing.indices.items():
        for suffix, value in indexing_unit.items():
            print(prefix, suffix, value)
```
If the submodels are also converted to pydantic `BaseModel` (as they should) you can drop the `.items()` call.
```python
    for prefix, indexing_unit in beg_thing.indices:
        for suffix, value in indexing_unit:
            print(prefix, suffix, value)
```

2020-11-10 13:38 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +            if value:
I agree, it should explicitly check `value is None`.

2020-11-10 13:38 UTC, RmStorm commented on src/odm2_postgres_api/routes/begroing_routes.py
> +        directiveids=new_indices.project_ids,
Pretty much this whole endpoint starting from the `post_actions()` call must be wrapped in a transaction like so:
```python
async with connection.transaction():
```

2020-11-12 16:26 UTC, roryscot commented on src/odm2_postgres_api/schemas/schemas.py
> +class BasicIndexingUnit(Dict):
Ya, I was getting weird linting errors on the routes

2020-11-12 16:38 UTC, roryscot commented on tests/test_begroing.py
> +    index_data = (
This was something that Black changed on save

2020-11-12 16:39 UTC, roryscot commented on src/odm2_postgres_api/schemas/schemas.py
> +    nEQR: Optional[float]
src/odm2_postgres_api/routes/begroing_routes.py:237: error: Value of type "IndexingInfo" is not indexable
src/odm2_postgres_api/routes/begroing_routes.py:239: error: "BasicIndexingUnit" has no attribute "get"
src/odm2_postgres_api/routes/begroing_routes.py:241: error: No overload variant of "__add__" of "tuple" matches argument type "str"
src/odm2_postgres_api/routes/begroing_routes.py:241: note: Possible overload variants:
src/odm2_postgres_api/routes/begroing_routes.py:241: note:     def __add__(self, Tuple[Any, ...]) -> Tuple[Any, ...]

2020-11-26 16:04 UTC, merged